FROM nginx:1.25-alpine

COPY nginx.ssl.template  /etc/nginx/nginx.ssl.template
COPY nginx.http.template /etc/nginx/nginx.http.template
COPY docker-entrypoint-nginx.sh /docker-entrypoint-nginx.sh
RUN chmod +x /docker-entrypoint-nginx.sh

ENTRYPOINT ["/docker-entrypoint-nginx.sh"]
CMD ["nginx", "-g", "daemon off;"]
